### ISSUE TITLE
Content Security Policy prohibits use of space logo images

### ISSUE THREAD

**Issue by ofeldt** [gidsi/eva-frontend#1]
**Given** a properly constructed Space API JSON Object
**When** I add a "logo"-field to my JSON Object with an HTTPS-URL to an image
**Then** this image is to be displayed in the Marker Popup Component after clicking it.
**But** not the following Content Security Policy Error in my browser console:
  `"Refused to load the image 'https://[...]' because it violates the following Content Security Policy directive: "img-src 'self' data: blob: filesystem:  ".`

**Comment by gidsi** [comment]
Hi!

This is a server issue and not a frontend issue.

We're working on it.

**Comment by astro** [comment]
Issue persists.

**Comment by saerdnaer** [comment]
@ruebezahl Whats the best solution to resolve this issue?

**Comment by gidsi** [comment]
Because it seems to bother a few of you guys, 74a670b fixes that.
