### ISSUE TITLE
Documentation missing for proper usage

### ISSUE THREAD

**Issue by ofeldt** [gidsi/eva-frontend#2]
**Given** I'm new to this
**When** I want to add my local space properly to an instance of this frontend
**Then** I expect a tutorial mentioning which fields to add to my Space API JSON Object
**And** which constraints those fields have
**But** not having to read the frontend code to find out about field constraints.

**Comment by gidsi** [comment]
Hi!

This is not the space API Project, we're just using it. Space API Documentation can be found under http://spaceapi.net/
