### ISSUE TITLE
Highlight on map when hovering over event

### ISSUE THREAD

**Issue by ofeldt** [gidsi/eva-frontend#3]
**Given** I visit the index page
**When** I hover over a event (EventList > TableRow)
**Then** I see the corresponding space getting _highlighted_ on the map

**Comment by gidsi** [comment]
Hi!

Cause you can just see the map and around five events on a fullHD screen on the main page i wouldn't recommend that, but feel free to implement it by yourself. 

Please be aware that it could be removed when we implement the filter for spaces again.
