### ISSUE TITLE
spaceapi disconnected

### ISSUE THREAD

**Issue by viisauksena** [gidsi/eva-frontend#5]
there are no spaces at all

**Comment by saerdnaer** [comment]
fixed

**Comment by viisauksena** [comment]
funny , since some days it was disconnected again. So no data there 
and now , a shec revealed a server error https://spaceapi.ccc.de/
... btw. thx for the work

**Comment by gidsi** [comment]
Yeah, we had a system update today and some problems with the involved daemon, should be not as flappy anymore :)
