### ISSUE TITLE
calendar update frequency

### ISSUE THREAD

**Issue by viisauksena** [gidsi/eva-frontend#8]
how high is the frequency ... of update for calendar ics, 
for Freiburg we see that there are strange / or outdated entrys only included
https://cccfr.de/calendar.ics
if so, i would be happy to dig deeper ... 
... - ping (after small talk in Lohra)

**Comment by viisauksena** [comment]
so for this friday they should be at least 2 dates for example,
beside the mentioned ics file - this link may be interesting https://cccfr.de/calendar/

**Comment by gidsi** [comment]
Hi! 

I remembered the problem now, thought i already send you an email about it before :)

The problem with your calendar is the dateformat in the until area of the rrule. 

Example:
```
RRULE:FREQ=WEEKLY;BYDAY=TH;UNTIL=20171113T0123
```
should be
```
RRULE:FREQ=WEEKLY;BYDAY=TH;UNTIL=20171113T012300Z
```

the important paragraphs from the rfc
--------------
**rrule until:**
> The UNTIL rule part defines a date-time value which bounds the recurrence rule in an inclusive manner. If the value specified by UNTIL is synchronized with the specified recurrence, this date or date-time becomes the last instance of the recurrence. If specified as a date-time value, then it MUST be specified in an UTC time format. If not present, and the COUNT rule part is also not present, the RRULE is considered to repeat forever.

**date-time utc:**
> The date with UTC time, or absolute time, is identified by a LATIN CAPITAL LETTER Z suffix character (US-ASCII decimal 90), the UTC designator, appended to the time value. For example, the following represents January 19, 1998, at 0700 UTC:
> DTSTART:19980119T070000Z

**Welcome to ical hell!**
